### PR TITLE
add files from day1 to day4

### PR DESCRIPTION
**Pull request by kaustubh1412**

### CODE REVIEW

**Comment by shash137** [comment]
@kaustubh1412 add time and space complexities and approach of your code.

**Comment by shash137** [comment]
Yes @kaustubh1412  go ahead.

**Comment by shash137** [comment]
@kaustubh1412  I'm merging this one, but make sure to add in all the file from next time.

**Comment by kaustubh1412** [comment]
@shash137 yes I'll keep that in mind. I added these details in all the files now. 

PS: I actually added these details for each file while uploading them in the repo as a commit comment, but I guess they're not visible in the pull requests, my bad

**Pull request merged**
